package org.example.dal.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 *
 * create By Grant
 * 2024-04-28 23:33:45
 * 表名： ord_order
 *
 */
@Accessors(chain = true)
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class OrdOrder implements Serializable {
    public static final Byte IS_DELETED = DeleteFlag.DISABLE.value();

    public static final Byte NOT_DELETED = DeleteFlag.ENABLE.value();

    private Long id;

    /**
     * Database Column Remarks:
     *   订单号
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   状态
     */
    private Integer statusCd;

    /**
     * Database Column Remarks:
     *   总金额
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   删除状态[enable(0):未删除, disable(1):已删除]
     */
    private Byte deleteFlag;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private LocalDateTime createdTime;

    private static final long serialVersionUID = 1L;

    public void andLogicalDeleted(boolean deleted) {
        setDeleteFlag(deleted ? DeleteFlag.DISABLE.value() : DeleteFlag.ENABLE.value());
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ord_order
     *
     * @mbg.generated
     */
    public static enum DeleteFlag {
        ENABLE(Byte.valueOf("0"), "未删除"),
        DISABLE(Byte.valueOf("1"), "已删除");

        private final Byte value;

        private final String name;

        DeleteFlag(Byte value, String name) {
            this.value = value;
            this.name = name;
        }

        public Byte getValue() {
            return this.value;
        }

        public Byte value() {
            return this.value;
        }

        public String getName() {
            return this.name;
        }

        public static DeleteFlag parseValue(Byte value) {
            if (value != null) {
                for (DeleteFlag item : values()) {
                    if (item.value.equals(value)) {
                        return item;
                    }
                }
            }
            return null;
        }

        public static DeleteFlag parseName(String name) {
            if (name != null) {
                for (DeleteFlag item : values()) {
                    if (item.name.equals(name)) {
                        return item;
                    }
                }
            }
            return null;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ord_order
     *
     * @mbg.generated
     */
    public static enum Column {
        id("id", "id", "BIGINT", false),
        orderId("order_id", "orderId", "VARCHAR", false),
        statusCd("status_cd", "statusCd", "TINYINT", false),
        amount("amount", "amount", "DECIMAL", false),
        deleteFlag("delete_flag", "deleteFlag", "TINYINT", false),
        createdTime("created_time", "createdTime", "TIMESTAMP", false);

        private static final String BEGINNING_DELIMITER = "'";

        private static final String ENDING_DELIMITER = "'";

        private final String column;

        private final boolean isColumnNameDelimited;

        private final String javaProperty;

        private final String jdbcType;

        public String value() {
            return this.column;
        }

        public String getValue() {
            return this.column;
        }

        public String getJavaProperty() {
            return this.javaProperty;
        }

        public String getJdbcType() {
            return this.jdbcType;
        }

        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        public static Column[] all() {
            return Column.values();
        }

        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}